Fix compiling LaTeX code containing TikZ macros.
The problem. When compiling LaTeX code with tikz macros, the following error happens:
```
! Package tikz Error: Sorry, some package has redefined the meaning of the math-mode dollar sign. This is incompatible with tikz and its calc library and might cause unrecoverable errors.
```

The cause. TikZ seems to be not compatible with 'preview' package.
https://tex.stackexchange.com/a/536029/222496
> The compilation error is expected since the preview package redefines $. From the manual:
>> textmath will make all text math subject to previews. Since math mode is used thoroughly inside of LaTX even for other purposes, this works by redefining \(, \) and $ and the math environment (apparently some people use that). Only occurrences of these text math delimiters in later loaded packages and in the main document will thus be affected.

The solution. Use '\documentclass[preview]{standalone}' instead.